-- Create custom_notifications table
CREATE TABLE IF NOT EXISTS public.custom_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.custom_notifications ENABLE ROW LEVEL SECURITY;

-- 1. Policy: Users can view their own custom notifications or global ones
CREATE POLICY "Users can view their own custom notifications."
    ON public.custom_notifications
    FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id OR user_id IS NULL);

-- 2. Policy: Users can insert their own custom notifications
CREATE POLICY "Users can insert their own custom notifications."
    ON public.custom_notifications
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);

-- 3. Policy: Users can update their own custom notifications
CREATE POLICY "Users can update their own custom notifications."
    ON public.custom_notifications
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- 4. Policy: Users can delete their own custom notifications
CREATE POLICY "Users can delete their own custom notifications."
    ON public.custom_notifications
    FOR DELETE
    TO authenticated
    USING (auth.uid() = user_id);

-- 5. Auto-cleanup function to delete notifications older than 24 hours (1 day)
CREATE OR REPLACE FUNCTION public.delete_old_custom_notifications()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM public.custom_notifications 
    WHERE created_at < NOW() - INTERVAL '1 day';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. Trigger to run cleanup automatically after inserting a new notification
CREATE OR REPLACE TRIGGER trigger_delete_old_custom_notifications
AFTER INSERT ON public.custom_notifications
FOR EACH STATEMENT
EXECUTE FUNCTION public.delete_old_custom_notifications();
-- 7. Enable real-time for custom_notifications table
ALTER PUBLICATION supabase_realtime ADD TABLE public.custom_notifications;


-- ──────────────────────────────────────────────────────────────────
-- 📋 EXAMPLE ROW INSERT (Run this to test)
-- ──────────────────────────────────────────────────────────────────
-- INSERT INTO public.custom_notifications (content, user_id)
-- VALUES (
--     'This is a special one-time insight! 🌟 Make sure to get some fresh air.', 
--     (SELECT id FROM auth.users LIMIT 1) -- Automatically grabs the first user ID in your database to test
-- );

