import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';
import '../providers/cycle_provider.dart';

class PdfExportService {
  /// Generates and shares a beautiful PDF medical report
  static Future<void> generateAndShareDoctorReport(
      CycleProvider provider) async {
    final pdf = pw.Document(
      title: '${provider.userName} - Lunara Medical Report',
      author: 'Lunara Health App',
    );

    // Try to load a custom font for better formatting, fallback to default if it fails
    pw.Font? regularFont;
    pw.Font? boldFont;
    try {
      regularFont =
          pw.Font.ttf(await rootBundle.load("fonts/Inter-Regular.ttf"));
      boldFont = pw.Font.ttf(await rootBundle.load("fonts/Inter-Bold.ttf"));
    } catch (e) {
      // Ignore if fonts aren't bundled
    }

    final theme = pw.ThemeData.withFont(
      base: regularFont ?? pw.Font.helvetica(),
      bold: boldFont ?? pw.Font.helveticaBold(),
    );

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          theme: theme,
          margin: const pw.EdgeInsets.all(40),
          pageFormat: PdfPageFormat.a4,
        ),
        header: (context) => _buildHeader(provider),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildPatientOverview(provider),
          pw.SizedBox(height: 30),
          _buildCycleMetrics(provider),
          pw.SizedBox(height: 30),
          _buildSymptomSummary(provider),
          pw.SizedBox(height: 30),
          _buildDailyLogSection(provider),
        ],
      ),
    );

    // Open the native share/print dialog
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name:
          'Lunara_Report_${DateFormat('MMM_yyyy').format(DateTime.now())}.pdf',
    );
  }

  static pw.Widget _buildHeader(CycleProvider provider) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Lunara Health Report',
              style: pw.TextStyle(
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
                color: const PdfColor.fromInt(0xFF3E2723),
              ),
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'Generated On',
                  style: const pw.TextStyle(
                      fontSize: 10, color: PdfColors.grey700),
                ),
                pw.Text(
                  DateFormat('MMMM d, yyyy').format(DateTime.now()),
                  style: pw.TextStyle(
                      fontSize: 12, fontWeight: pw.FontWeight.bold),
                ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Container(height: 2, color: const PdfColor.fromInt(0xFFFF8989)),
        pw.SizedBox(height: 20),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Text(
        'Page ${context.pageNumber} of ${context.pagesCount} • Generated by Lunara',
        style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
      ),
    );
  }

  static pw.Widget _buildPatientOverview(CycleProvider provider) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: const PdfColor.fromInt(0xFFFDFBF7),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border.all(color: const PdfColor.fromInt(0xFFEFEBE1)),
      ),
      child: pw.Row(
        children: [
          _buildInfoColumn('Patient Name', provider.userName),
          _buildInfoColumn('Age',
              provider.age > 0 ? '${provider.age} years' : 'Not provided'),
          _buildInfoColumn('BMI',
              provider.bmi > 0 ? provider.bmi.toStringAsFixed(1) : 'N/A'),
        ],
      ),
    );
  }

  static pw.Widget _buildInfoColumn(String label, String value) {
    return pw.Expanded(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label,
              style:
                  const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          pw.SizedBox(height: 4),
          pw.Text(value,
              style:
                  pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static pw.Widget _buildCycleMetrics(CycleProvider provider) {
    final nextPeriod = provider.nextPeriodDate != null
        ? DateFormat('MMM d, yyyy').format(provider.nextPeriodDate!)
        : 'Unknown';

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Cycle Metrics'),
        pw.SizedBox(height: 10),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            _buildMetricCard('Average Length', '${provider.cycleLength} Days'),
            pw.SizedBox(width: 10),
            _buildMetricCard(
                'Period Duration', '${provider.periodDuration} Days'),
            pw.SizedBox(width: 10),
            _buildMetricCard('Next Predicted', nextPeriod),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildMetricCard(String label, String value) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.symmetric(vertical: 12, horizontal: 8),
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: const PdfColor.fromInt(0xFFFFE0B2)),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Text(value,
                style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: const PdfColor.fromInt(0xFFF57C00))),
            pw.SizedBox(height: 4),
            pw.Text(label,
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
                textAlign: pw.TextAlign.center),
          ],
        ),
      ),
    );
  }

  static pw.Widget _buildSymptomSummary(CycleProvider provider) {
    final history = provider.getSymptomFrequency(30);
    final topSymptoms = history.entries.take(5).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Top Symptoms (Last 30 Days)'),
        pw.SizedBox(height: 10),
        if (topSymptoms.isEmpty)
          pw.Text('No symptoms were logged in the last 30 days.',
              style: pw.TextStyle(fontStyle: pw.FontStyle.italic))
        else
          pw.Wrap(
            spacing: 8,
            runSpacing: 8,
            children: topSymptoms.map((entry) {
              final name = entry.key.replaceAll('_', ' ');
              return pw.Container(
                padding:
                    const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                decoration: pw.BoxDecoration(
                  color: const PdfColor.fromInt(0xFFFBE9E7),
                  borderRadius:
                      const pw.BorderRadius.all(pw.Radius.circular(15)),
                ),
                child: pw.Text(
                  '$name: ${entry.value} days',
                  style: pw.TextStyle(
                      color: const PdfColor.fromInt(0xFFD84315),
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold),
                ),
              );
            }).toList(),
          ),
      ],
    );
  }

  static pw.Widget _buildDailyLogSection(CycleProvider provider) {
    final history = provider.getWellnessHistory(30);
    // Filter to only days where something was actually logged
    final logDays = history
        .where((day) =>
            day['water'] > 0 ||
            day['steps'] > 0 ||
            (day['symptoms'] as List).isNotEmpty)
        .toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Detailed Daily Log'),
        pw.SizedBox(height: 10),
        if (logDays.isEmpty)
          pw.Text('No detailed daily logs found.',
              style: pw.TextStyle(fontStyle: pw.FontStyle.italic))
        else
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
                fontSize: 10),
            headerDecoration:
                const pw.BoxDecoration(color: PdfColor.fromInt(0xFF3E2723)),
            cellStyle: const pw.TextStyle(fontSize: 9),
            cellPadding: const pw.EdgeInsets.all(6),
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            headers: ['Date', 'Symptoms', 'Mood', 'Sleep', 'Water', 'Steps'],
            data: logDays.map((day) {
              final date = day['date'] as DateTime;
              final symptoms =
                  (day['symptoms'] as List).join(', ').replaceAll('_', ' ');
              return [
                DateFormat('MMM d').format(date),
                symptoms.isEmpty ? '-' : symptoms,
                day['mood'],
                '${day['sleep']}h',
                '${day['water']} gls',
                '${day['steps']}st',
              ];
            }).toList(),
          ),
      ],
    );
  }

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Text(
      title.toUpperCase(),
      style: pw.TextStyle(
        fontSize: 12,
        fontWeight: pw.FontWeight.bold,
        color: const PdfColor.fromInt(0xFF3E2723),
        letterSpacing: 1,
      ),
    );
  }
}
